name: publish

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: |
          dotnet build --configuration Release --no-restore

      - name: Test
        run: |
          dotnet test --no-restore --verbosity normal

      - name: Publish
        run: |
          mkdir /build
          dotnet publish /p:PublishProfile=./Properties/PublishProfiles/FolderProfile.pubxml --output /build

      - name: Attach files to Github releases
        uses: softprops/action-gh-release@v1
        with:
          files: "/build/*.exe"
          fail_on_unmatched_files: true
